.SETCPU "HUC6280"

.SEGMENT "ZEROPAGE"
POINTER: 	.RES 2
JOYPAD:		.RES 1

.SEGMENT "CODE"

RESET:
    SEI		;DISABLE INTERRUPTS DURING INITIALIZATION
    CLD		;CLEAR DECIMAL MODE
	CSH		;HIGH SPEED MODE

	LDA #$F8		;SET RAM BANK TO MPR1
	TAM #%00000010	;TAM1 ($2000-$3FFF)
	LDA #$FF		;SET I/O BANK TO MAPR0
	TAM #%00000001	;TAM0 ($0000-$1FFF)
	TAX
	TXS				;INITIALIZE STACK POINTER

	;T12 - TIQ, IRG1, IRQ2
	LDA #%00000111
	STA $1402			;IRQ MASK 1-OFF
	

	;CLEAR RAM ($2000-$3FFF)
		;FIRST ZERO PAGE CLEAR
		CLX
		CLA
		:
			STA $00, X
			INX
			BNE :-
	CLY
	CLX
	LDA #$21
	STA POINTER+1
	CLA
	STA POINTER
	:
		STA (POINTER), Y
		INY
		BNE :-
		INC POINTER+1
		INX
		CPX #$1F
		BNE :-

	;CLEAR VRAM
	CLY
	CLX
	ST0 #$00		;VRAM WRITE POINTER
	ST1 #$00
	ST2 #$00		;SET VRAM ADDRESS TO $0000
	ST0 #$02		;VRAM DATA WRITE LATCH
	:
		ST1 #$00
		ST2 #$00
		INY
		BNE :-
		INX
		CPX #$80
		BNE :-

	;SET BG TILEMAP SIZE
	ST0 #$09		;MEMORY ACCESS WIDTH REGISTER
	ST1 #$00		;32x32
	ST2 #$00
	
	;SET 256x240 SCREEN
	ST0 #$0A	;HORIZONTAL SYNC REGISTER MUST BE #$0202
	ST1 #$02
	ST2 #$02
	ST0 #$0B	;HORIZONTAL DISPLAY REGISTER MUST BE #$031F
	ST1 #$1F
	ST2 #$03
	ST0 #$0C	;VERTICAL SYNC REGISTER MUST BE #$0F02
	ST1 #$02
	ST2 #$0F
	ST0 #$0D	;VERTICAL DISPLAY REGISTER MUST BE #$00EF
	ST1 #$EF
	ST2 #$00
	ST0 #$0E	;VERTICAL DISPLAY END POSITIONREGISTER MUST BE #$0003
	ST1 #$03
	ST2 #$00
	
	;SET BACKGROUND PALETTE
	STZ $0402	;PALETTE ADDRESS LOW
	STZ $0403	;PALETTE ADDRESS HIGH
	
	;BACKGROUND PALETTE
	TIA PALETTE, $0404, 512	;AUTO INCREMENTS TO NEX INDEX AFTER $0405 ACCESS
	;SPRITE PALETTE
	TIA PALETTE, $0404, 512	;AUTO INCREMENTS TO NEX INDEX AFTER $0405 ACCESS

	;LOADING SPRITE DATA
		;LOAD TILES TO VRAM $1000
		ST0 #$00	;VRAM WRITE POINTER
		ST1 #$00	;LOW
		ST2 #$10	;HIGH
		ST0 #$02	;VRAM WRITE REGISTER
		TIA SPRITETILES, $0002, 100	;COPY AND LOOP
		
		ST0 #$00	;VRAM WRITE POINTER 
		ST1 #$00
		ST2 #$7F	;VRAM ADDRESS = $7F00
		ST0 #$02	;VRAM WRITE REGISTER
		TIA SATBINIT, $0002, 8	;COPY INITIAL SPRITE VALUES
	
	;SCREEN INIT
	ST0 #$05			;SELECT VDC CONTROL REGISTER
	ST1 #%11001000		;BACKGROUND ON, SPRITES ON + VBLANK INT ENABLE
	ST2 #$00
	ST0 #$09			;MEMORY ACCESS WIDTH REGISTER
	ST1 #%00000000		;BACKGROUNG TILEMAP SIZE (32x32)
	ST2 #$00

	;RESET BACKGROUND SCROLL REGISTERS
	ST0 #$07			;BACKGROUND X SCROLL REGISTER
	ST1 #$00
	ST2 #$00
	
	ST0 #$08			;BACKGROUND Y SCROLL REGISTER
	ST1 #$00
	ST2 #$00

	;ALLOW INTERRUPTS
	LDA #%00000101      ;ENABLE VBLANK INTERRUPT (DISABLE EXTERNAL + TIMER)
    STA $1402           ;IRQ DISABLE REGISTER 
	LDA $0100			;READ VDC STATUS
	CLI

    ;INFINITE LOOP
WAITNMI:
    BRA WAITNMI

NMI:
	RTI

VBLANK:
	PHA
	LDA $0100 ;READ VDC STATUS REGISTER
	;CHECK JOYPAD
	JSR READJOYPAD
	
	;DMA FROM VRAM TO SATB (MUST SET ADDRESS AND START DMA ON EVERY FRAME)
	;DEFINE SATB LOCATION IN VRAM AT $7F00
	ST0 #$13		;SATB DMA SRC ADDRESS
	ST1 #$00
	ST2 #$7F
	;START AUTO TRANSFER OF SPRITE DATA FROM VRAM TO SATB
	ST0 #$0F		;DMA CONTROL REGISTER
	ST1 #%00001000	;SATB DMA AUTO TRANSFER ON
	ST2 #$08
	
	PLA
	RTI
	
READJOYPAD:
	;1 UP, 0 DOWN
	;RESET MULTITAP
	LDA #$01	;RESET MULTITAP 1
	JSR SENDJOYPADCOMMAND
	LDA #$03	;RESET MULTITAP 2
	JSR SENDJOYPADCOMMAND
	
	READCONTROLLER1:
		LDA #$01
		JSR SENDJOYPADCOMMAND
		LDA $1000	;(LRUD)
		ASL
		ASL
		ASL
		ASL
		STA JOYPAD
		LDA #$00
		JSR SENDJOYPADCOMMAND
		LDA $1000	;(RSBA)
	
	RTS
SENDJOYPADCOMMAND:
	STA $1000	;JOYPAD I/O PORT
	NOP
	NOP
	NOP
	RTS

.SEGMENT "VECTORS"
    .WORD 0			;IRQ2 (BRK AND EXTERNAL INT)
    .WORD VBLANK	;IRQ1 VDC INTERRUPT (VSYNC)
    .WORD 0			;TIMER INTERRUPT
	.WORD NMI		;NMI
    .WORD RESET		;RESET VECTOR
	
.SEGMENT "ROMDATA"
	SPRITETILES:
		.INCBIN "TILES.CHR"
	SATBINIT:
		;Y-64, X-32, TILEADDRESS/32, ATTR
		.WORD $00B8, $0098, $0080, $0000	;8 BYTES PER SPRITES
	PALETTE:
		.INCBIN "COLOR.PAL"